### ISSUE TITLE
Move HTTP client to manticore

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-output-http#10]

**Comment by jordansissel** [comment]
Background:

* We currently use FTW which is a library I maintain. I'd love if FTW were no longer needed because it's one less thing to maintain for me. 
* Further, FTW uses nonblocking socket calls and under JRuby, this doesn't work correctly (we'll fix this eventually, but not today)
* We moved to using Manticore for elasticsearch-ruby a while ago with some good success.
