### ISSUE TITLE
logstash http output fails to work with ssl

### ISSUE THREAD

**Issue by Vehyla** [logstash-plugins/logstash-output-http#33]
When using the http output and specifying a keystore I see the following error:

NoMethodError: undefined method `toCharArray' for nil:NilClass
                        get_store at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.2-java/lib/manticore/client.rb:637
                              tap at org/jruby/RubyKernel.java:1858
                        get_store at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.2-java/lib/manticore/client.rb:635
                  setup_key_store at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.2-java/lib/manticore/client.rb:597
  ssl_socket_factory_from_options at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.2-java/lib/manticore/client.rb:573
                     pool_builder at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.2-java/lib/manticore/client.rb:364
                             pool at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.2-java/lib/manticore/client.rb:372
                       initialize at /opt/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.5.2-java/lib/manticore/client.rb:192
                      make_client at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-mixin-http_client-2.2.1/lib/logstash/plugin_mixins/http_client.rb:164
                           client at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-mixin-http_client-2.2.1/lib/logstash/plugin_mixins/http_client.rb:169
                          receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-http-2.1.1/lib/logstash/outputs/http.rb:117
                    multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-http-2.1.1/lib/logstash/outputs/http.rb:93
                             each at org/jruby/RubyArray.java:1613
                    multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-http-2.1.1/lib/logstash/outputs/http.rb:93
             worker_multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/output_delegator.rb:119
                    multi_receive at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/output_delegator.rb:65
                     output_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:290
                             each at org/jruby/RubyHash.java:1342
                     output_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:290
                      worker_loop at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:221
                    start_workers at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:190

Using the following output
output {
  http {
    url => "https://our-ssl.elb.amazon.com"
    http_method => "put"
    keystore => "/opt/logstash/pki/keystore.jks"
  }
}

**Comment by floragunncom** [comment]
same here

<pre>
Pipeline aborted due to error {:exception=>#<NoMethodError: undefined method `toCharArray' for nil:NilClass>, :backtrace=>["/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:667:in `get_store'", "org/jruby/RubyKernel.java:1858:in `tap'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:665:in `get_store'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:627:in `setup_key_store'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:603:in `ssl_socket_factory_from_options'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:394:in `pool_builder'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:402:in `pool'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/manticore-0.5.5-java/lib/manticore/client.rb:208:in `initialize'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/manticore.rb:100:in `__build_connections'", "org/jruby/RubyArray.java:2414:in `map'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/manticore.rb:90:in `__build_connections'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:34:in `initialize'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/client.rb:115:in `initialize'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport.rb:26:in `new'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.5-java/lib/logstash/outputs/elasticsearch/http_client.rb:129:in `build_client'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.5-java/lib/logstash/outputs/elasticsearch/http_client.rb:20:in `initialize'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.5-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:40:in `build'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.5-java/lib/logstash/outputs/elasticsearch.rb:132:in `build_client'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.5-java/lib/logstash/outputs/elasticsearch/common.rb:14:in `register'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/output_delegator.rb:75:in `register'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:181:in `start_workers'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:136:in `run'", "/Users/temp/search-guard-ssl/logstash-2.3.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/agent.rb:465:in `start_pipeline'"], :level=>:error}
</pre>

**Comment by kares** [comment]
`NoMethodError: undefined method `toCharArray' for nil:NilClass`
I do not think this is relevant with recent 7.x Logstash versions, the issue might have been specific to Manticore 0.5.2
